### ISSUE TITLE
[BUG/DOC] Optional dependencies aren't optional

### ISSUE THREAD

**Issue by fkantelberg** [icgood/pymap#159]
Hello,

while testing your awesome project again with a more minimal setup than your docker containers (these are working great) I stumbled over many import issues because the optional dependencies aren't optional as stated in the pyproject.toml and readme.

```console
-> % docker run --rm -it python:3.11 bash
root@af3ee079953c:/# pip install pymap
Collecting pymap
  Downloading pymap-0.35.1-py3-none-any.whl (213 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.7/213.7 kB 2.1 MB/s eta 0:00:00
Collecting proxy-protocol~=0.11.1 (from pymap)
  Downloading proxy_protocol-0.11.1-py3-none-any.whl (32 kB)
Collecting pysasl~=1.0 (from pymap)
  Downloading pysasl-1.0.2-py3-none-any.whl (22 kB)
Collecting typing-extensions (from proxy-protocol~=0.11.1->pymap)
  Downloading typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Installing collected packages: typing-extensions, pysasl, proxy-protocol, pymap
Successfully installed proxy-protocol-0.11.1 pymap-0.35.1 pysasl-1.0.2 typing-extensions-4.6.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv           
root@af3ee079953c:/# pymap --help                                                                                   
```

**Exception:** (one of them)
```
...
File "/usr/local/lib/python3.11/site-packages/pymap/backend/redis/__init__.py", line 17, in <module>
    from redis.asyncio import Redis, WatchError
ModuleNotFoundError: No module named 'redis'
```

This would mean quite a lot of catching of ImportError and handling them if you want to achieve a runnable project also with minimal dependencies. Otherwise you could update the readme to use `pip install pymap[redis,admin,macaroon,sieve,swim,optional]` instead of `pip install pymap`. Using the minimal requirements still works great if used as library.

**Comment by icgood** [comment]
Well that's annoying, seems I've been bitten by the deprecation of using extras in entry points:

https://packaging.python.org/en/latest/specifications/entry-points/#data-model

> Using extras for an entry point is no longer recommended. Consumers should support parsing them from existing distributions, but may then ignore them. New publishing tools need not support specifying extras. The functionality of handling extras was tied to setuptools’ model of managing ‘egg’ packages, but newer tools such as pip and virtualenv use a different model.

Some cursory research it seems like there's (currently) no way to programmatically check for extras, so I'll have to do it the hard way.

**Comment by icgood** [comment]
Each set of extra dependencies now has a list of symbols in a packaged toml file such that the plugin (e.g. redis backend) is filtered if the symbols cannot import. It's a bit redundant but importlib doesn't provide any other way that I could find.

**Comment by icgood** [comment]
Thanks for the report, it was an actual bug / regression not bad docs :)
